query getTreeNodes(
  $rtId: OctoObjectId!
  $ckTypeId: String!
  $directRoleId: String!
  $directTargetCkTypeId: String!,
  $indirectRoleId: String!
  $indirectTargetCkTypeId: String!
) {
  runtime {
    runtimeEntities(rtId: $rtId, ckId: $ckTypeId) {
      items {
        rtId
        rtDisplayName
        rtDisplayDescription
        ckTypeId
        associations {
          targets(
            roleId: $directRoleId
            ckId: $directTargetCkTypeId
            direction: INBOUND
          ) {
            items {
              rtId
              rtDisplayName
              rtDisplayDescription
              ckTypeId
              associations {
                targets(
                  roleId: $indirectRoleId
                  ckId: $indirectTargetCkTypeId
                  direction: INBOUND
                ) {
                  totalCount
                }
              }
            }
          }
        }
      }
    }
  }
}
