query getTrees($ckTypeId: String!) {
  runtime {
    runtimeEntities(ckId: $ckTypeId) {
      items {
        rtId
        rtDisplayName
        rtDisplayDescription
        ckTypeId
        attributes(attributeNames: ["name", "description"]) {
          items {
            attributeName
            value
          }
        }
        associations {
          targets(
            roleId: "System/ParentChild"
            ckId: "Basic/TreeNode"
            direction: INBOUND
          ) {
            totalCount
          }
        }
      }
    }
  }
}
