name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - test/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys-mm-cloud
  - group: OctoDefault
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: isTest
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/test') }}

stages:
  - stage: Build
    jobs:
      - job: linux
        displayName: npm build
        pool:
          name: meshmakers-ci-agents
        steps:
          - template: update-build-number.yml
          - template: set-version.yml
          - template: setup-telerik-license.yml
          - template: run-tests.yml

          # Publish @meshmakers/* npm packages (in dependency order)
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:shared-services'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/shared-services'
              libName: 'shared-services'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:shared-auth'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/shared-auth'
              libName: 'shared-auth'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:octo-services'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/octo-services'
              libName: 'octo-services'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:shared-ui'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/shared-ui'
              libName: 'shared-ui'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:octo-ui'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/octo-ui'
              libName: 'octo-ui'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:octo-process-diagrams'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/octo-process-diagrams'
              libName: 'octo-process-diagrams'
          - template: npm-publish-to-npmjs.yml
            parameters:
              npmCommand: 'build:octo-meshboard'
              buildWorkingDirectory: 'src/frontend-libraries'
              publishWorkingDirectory: 'src/frontend-libraries/dist/meshmakers/octo-meshboard'
              libName: 'octo-meshboard'
          - template: build-and-push-docker-image.yml
            parameters:
              PublicRegistryServiceConnection: $(DockerRegistryPublicConnection)
              PrivateRegistryName: $(DockerRegistryPrivateUri)
              Repository: meshmakers/octo-mesh-template-app
              Dockerfile: src/frontend-libraries/Dockerfile
          - template: handle-artifacts.yml
