FROM nginx:1.27.2-bookworm
WORKDIR /usr/share/nginx/html
EXPOSE 80
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh .
COPY demo-app/ .
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
