// @ts-check
const eslint = require("@eslint/js");
const tseslint = require("typescript-eslint");
const angular = require("angular-eslint");
const unusedImports = require("eslint-plugin-unused-imports");
const stylistic = require("@stylistic/eslint-plugin");

module.exports = tseslint.config(
  {
    // Global ignore (an `ignores`-only entry): generated by `npm run codegen` / the version
    // script, so it is never linted and never auto-fixed — the generator would reintroduce any
    // violation on the next run. Must be global, not an `ignores` on the rule block below:
    // a per-block ignore only drops the rules, leaves the file matched by other blocks, and
    // then the default (non-TypeScript) parser reports "Parsing error: Unexpected token".
    ignores: [
      // `**/*` rather than `**`: a bare `**` also matches the directory itself, ESLint then
      // stops descending into it and the un-ignore patterns below never take effect.
      "**/graphQL/**/*",
      // …except the hand-written files that live in those generated folders (checked against
      // codegen.yml): the small `globalTypes.ts` re-export stubs that satisfy codegen's
      // `baseTypesPath`, and legacy-demo-app's hand-written Apollo SDK client. The two large
      // real `globalTypes.ts` (octo-services, octo-ui/branding) and `possibleTypes.ts` are
      // codegen output and stay ignored.
      "!**/demo-app/src/app/graphQL/globalTypes.ts",
      "!**/octo-meshboard/src/lib/graphQL/globalTypes.ts",
      "!**/octo-process-diagrams/src/lib/graphQL/globalTypes.ts",
      "!**/octo-ui/src/lib/graphQL/globalTypes.ts",
      "!**/legacy-demo-app/src/app/graphQL/get-sdk-customers.ts",
      "**/environments/version.ts",
      "**/environments/currentVersion.ts"
    ],
  },
  {
    files: ["**/*.ts"],
    plugins: {
      "unused-imports": unusedImports,
      "@stylistic": stylistic,
    },
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      "no-restricted-imports": ["error", {
        "paths": [{
          "name": "@angular/platform-browser/animations",
          "importNames": ["NoopAnimationsModule", "BrowserAnimationsModule"],
          "message": "Use provideNoopAnimations() for tests (Kendo UI requires animation infrastructure), or provideAnimations() for app bootstrapping. Do not use the deprecated module imports."
        }]
      }],
      "unused-imports/no-unused-imports": "error",
      // .editorconfig, enforced (and auto-fixed) by ESLint rather than left to the editor:
      // 2-space indent, single quotes, final newline, no trailing whitespace.
      "@stylistic/indent": ["error", 2, { "SwitchCase": 1 }],
      "@stylistic/quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": "always" }],
      "@stylistic/eol-last": ["error", "always"],
      "@stylistic/no-trailing-spaces": "error",
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "app",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "app",
          style: "kebab-case",
        },
      ],
      "@typescript-eslint/no-unused-expressions": [
        "error",
        {
          "allowShortCircuit": true
        }
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          "args": "all",
          "argsIgnorePattern": "^_",
          "caughtErrors": "all",
          "caughtErrorsIgnorePattern": "^_",
          "destructuredArrayIgnorePattern": "^_",
          "varsIgnorePattern": "^_",
          "ignoreRestSiblings": true
        }
      ],
      // Enabled
      "@angular-eslint/prefer-standalone": "error",
      // angular-eslint 22 added this to the recommended set. The Angular 22
      // `change-detection-eager` migration explicitly set every existing
      // component to `ChangeDetectionStrategy.Eager` to preserve pre-v22
      // (CheckAlways) behavior. Forcing OnPush across the whole codebase is a
      // separate, behavioral change — out of scope for the version bump — so we
      // opt out of the rule here.
      "@angular-eslint/prefer-on-push-component-change-detection": "off",
      "no-empty": "error",
      "@typescript-eslint/no-empty-function": "error",
      "@angular-eslint/no-empty-lifecycle-method": "error",
      "@typescript-eslint/no-explicit-any": "error",
    },
  }
);
